name = "A wild theme for Hugo by Wild Tech 'Garden'"
copyright = "© 2023 Wild Tech 'Garden'"
description = """\
A theme for use by Wild Tech 'Garden' and others. Wraps \"'Wild' Theme \
Shell for Hugo by Wild Tech 'Garden'\"\
"""

[params]
## Sets 'green' as the default cssColourScheme when using this module
cssColourScheme = "green"

[module]
[module.hugoVersion]
extended = false
min = "v0.117.0"

[[module.imports]]
path = "github.com/wildtechgarden/wild-theme-shell-mod-hugo"
