name = "A wild theme for Hugo by Wild Tech 'Garden'"
copyright = "© 2023 Wild Tech 'Garden'"
description = """\
A theme for use by Wild Tech 'Garden' and others. Wraps \"'Wild' Theme \
Shell for Hugo by Wild Tech 'Garden'\"\
"""

[params]
## Sets 'green' as the default cssColourScheme when using this module
cssColourScheme = "green"

[module]
[module.hugoVersion]
extended = false
min = "v0.117.0"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "archetypes"
target = "archetypes"

[[module.imports]]
path = "github.com/wildtechgarden/wild-theme-shell-mod-hugo"

[[module.import.mounts]]
source = "static"
target = "static"

[[module.imports.mounts]]
source = "layouts"
target = "layouts"

[[module.imports.mounts]]
source = "data"
target = "data"

[[module.imports.mounts]]
source = "assets"
target = "assets"

[[module.imports.mounts]]
source = "i18n"
target = "i18n"

[[module.imports.mounts]]
source = "archetypes"
target = "archetypes"

