name = "A wild theme for Hugo by Wild Tech 'Garden'"
copyright = "© 2023 Wild Tech 'Garden'"
description = """\
A theme for use by Wild Tech 'Garden' and others. Wrapped in \"'Wild' Theme \
Shell for Hugo by Wild Tech 'Garden'\" -- very pre-alpha\
"""

[module]
[module.hugoVersion]
min = "0.117.0"
extended = true

[author]
name = "Daniel F. Dickinson for Wild Tech 'Garden'"
homepage = "https://www.danielfdickinson.ca/"
copyright = "© 2023 Wild Tech 'Garden'"
email = "dfdpublic@wildtechgarden.ca"
